import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const links = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "External Infinite Scroll",
    href: "/external",
  },
  {
    name: "Internal Infinite Scroll",
    href: "/internal",
  },
  {
    name: "Invalidate problem",
    href: "/invalidate",
  },
] as const;

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} dark`}>
      <body>
        <TRPCReactProvider>
          <nav className="flex items-center justify-center gap-4">
            {links.map((link) => (
              <Link key={link.name} href={link.href}>
                {link.name}
              </Link>
            ))}
          </nav>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
