import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <nav className="flex items-center justify-center gap-4">
            <Link href="/">Home</Link>
            <Link href="/external">External Infinite Scroll</Link>
            <Link href="/internal">Internal Infinite Scroll</Link>
          </nav>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
